# ~/.config/hypr/hyprpaper.conf
preload = ~/Pictures/wall1.png
preload = ~/Pictures/wall2.jpg
preload = ~/Pictures/wall3.png
preload = ~/Pictures/wall4.jpg
preload = ~/Pictures/wall5.jpg
preload = ~/Pictures/wall6.jpg
preload = ~/Pictures/wall7.jpg
preload = ~/Pictures/wall8.png
preload = ~/Pictures/wall9.jpg

# Set a default wallpaper on startup
wallpaper = , ~/Pictures/wall1.png
