#!/bin/bash

#xrandr --output LVDS1 --auto --output HDMI1 --auto --same-as LVDS1
#xrandr --output LVDS1 --auto --output HDMI1 --auto --right-of LVDS1
xrandr --output HDMI1 --auto --rotate normal --output eDP1 --auto --right-of HDMI1
